"""empty message

Revision ID: 05e6e598908c
Revises: cac18610d7e4
Create Date: 2021-05-21 19:32:21.466077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e6e598908c'
down_revision = 'cac18610d7e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.execute('Update artist SET seeking_venue = True WHERE seeking_venue IS NULL;')
    op.drop_column('artist', 'seeking_talent')
    op.execute('INSERT INTO artist (name, genres, city, state, phone, facebook_link, seeking_venue, image_link) VALUES(\'Matt Quevado\', \'Jazz\', \'New York\', \'NY\', \'300-400-5000\', \'https://www.facebook.com/mattquevedo923251523\', False, \'https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80\');')
    op.execute('INSERT INTO artist (name, genres, city, state, phone, seeking_venue, image_link) VALUES(\'The Wild Sax Band\', ARRAY[\'Jazz\', \'Classical\'], \'San Francisco\', \'CA\', \'432-325-5432\', False, \'https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80\');')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
